spring.application.name=bookstore

# MySQL Connection Settings
spring.datasource.url=jdbc:mysql://metro.proxy.rlwy.net:18557/railway
spring.datasource.username=root
spring.datasource.password=tZiimdXIRjBhItJMfQdEonQqraWgGuCY
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate Settings
spring.jpa.hibernate.ddl-auto=update
# Useful for debugging connection issues
spring.jpa.show-sql=true

# JWT Configuration
app.jwt.base64-secret=5xsSaeIX6DI8PZCYNIU6UW4knk5dqkP6WTdZATqWO3w=
# Access Token lifetime (ex: 15 minute = 900,000 ms)
app.jwt.access-token-expiration=900000
# Refresh Token lifetime (ex: 7 day)
app.jwt.refresh-token-expiration=604800000

# Pagination Configuration
spring.data.web.pageable.default-page-size=10
spring.data.web.pageable.max-page-size=100
spring.data.web.pageable.one-indexed-parameters=true